# Generated by Django 5.1.1 on 2024-10-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Наличными"), ("transfer", "Перевод на счет")],
                max_length=30,
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
