# Generated by Django 5.1.1 on 2024-10-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payments_payment_method"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payments",
        ),
    ]
