# Generated by Django 4.2.2 on 2024-10-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_delete_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последней авторизации"
            ),
        ),
    ]
